# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: go test .

    - name: Build
      run: go build main.go
      
    - name: Deploy to target
      run: |
        ssh-keyscan 192.168.105.3 > ~/.ssh/known_hosts
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/my_github_key && chmod 600 ~/.ssh/my_github_key
        ssh -l vagrant -i ~/.ssh/my_github_key 192.168.105.3 -C sudo systemctl stop myapp
        scp -i ~/.ssh/my_github_key main ${userName}@192.168.105.3:
        scp -i ~/.ssh/my_github_key myapp.service ${userName}@192.168.105.3:
        ssh -l vagrant -i ~/.ssh/my_github_key 192.168.105.3 -C sudo mv myapp.service /etc/systemd/system
        ssh -l vagrant -i ~/.ssh/my_github_key 192.168.105.3 -C sudo systemctl daemon-reload
        ssh -l vagrant -i ~/.ssh/my_github_key 192.168.105.3 -C sudo systemctl enable myapp
        ssh -l vagrant -i ~/.ssh/my_github_key 192.168.105.3 -C sudo systemctl start myapp

